name: Deploy Frontend to AWS ECS

on:
  push:
    branches:
      - develop
    paths:
      - 'FRONT_DESPACHO/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: innovatech-cluster
  SVC_FRONTEND: task-innovatech-frontend-service-z1dcso3a
  ECR_FRONTEND_REPO: innovatech-frontend

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # === MICROSERVICIO: FRONTEND ===
    - name: Build & Push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        
        ls -R .  
      ##docker build -t $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPO }}:latest ./FRONT_DESPACHO
        #docker push $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPO }}:latest

    - name: Deploy Frontend to Amazon ECS
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.SVC_FRONTEND }} --force-new-deployment