name: Deploy Backend to AWS EKS

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: innovatech-cluster
  ECR_VENTAS_REPO: innovatech-ventas
  ECR_DESPACHOS_REPO: innovatech-despachos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 🐳 1. Docker: Construcción y subida de Ventas
    - name: Build & Push Ventas to ECR
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_VENTAS_REPO }}:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_VENTAS_REPO }}:latest ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_VENTAS_REPO }} --all-tags

    # 🐳 2. Docker: Construcción y subida de Despachos
    - name: Build & Push Despachos to ECR
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_DESPACHOS_REPO }}:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_DESPACHOS_REPO }}:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_DESPACHOS_REPO }} --all-tags

    # ☸️ 3. Conectar con el clúster de AWS EKS y Desplegar Backend
    - name: Update Kubeconfig & Deploy to EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
        
        # Aplicar los manifiestos base del Backend y Base de datos
        kubectl apply -f k8s/01-mysql.yaml
        kubectl apply -f k8s/02-ventas.yaml
        kubectl apply -f k8s/03-despachos.yaml
        
        # Validador seguro: Solo aplica el frontend si el archivo existe en esta rama, si no, lo salta sin caerse
        if [ -f k8s/04-frontend.yaml ]; then
          kubectl apply -f k8s/04-frontend.yaml
        else
          echo "Saltando 04-frontend.yaml para evitar errores en esta rama."
        fi
        
        if [ -f k8s/05-hpa.yaml ]; then kubectl apply -f k8s/05-hpa.yaml; fi
        
        # Forzar actualización de contenedores del Backend
        kubectl set image deployment/ventas-deployment ventas-app=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_VENTAS_REPO }}:${{ github.sha }}
        kubectl set image deployment/despachos-deployment despachos-app=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_DESPACHOS_REPO }}:${{ github.sha }}