name: Pipeline CI/CD - Frontend AWS ECS (EP3)

on:
  push:
    branches:
      - develop  

env:
  AWS_REGION: us-east-1
  ECR_FRONTEND_REPO: innovatech-frontend
  ECS_CLUSTER: innovatech-cluster
  ECS_SERVICE_FRONT: svc-frontend

jobs:
  build-and-push-frontend:
    name: Build, Push Frontend to ECR and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3

    - name: Configurar Credenciales de AWS Academy
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar sesion en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & Push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPO }}:latest .
        docker push $ECR_REGISTRY/${{ env.ECR_FRONTEND_REPO }}:latest

    - name: Deploy Frontend to Amazon ECS
      run: aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_FRONT }} --force-new-deployment